---

- name: git clone Vundle.vim
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '{{bundle_root}}/Vundle.vim'
    version: master
    clone: yes
    update: yes
    force: yes

- name: Vundle Plugin Clean and Install
  shell: vim +PluginClean +qall & vim +PluginInstall +qall
  args:
    chdir: "{{config_root}}"
